name: Build and publish FastQC release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag or version string to use in artifact filenames when running manually (e.g., v0.12.1)'
        required: false
        default: 'dev'

permissions:
  contents: write

jobs:
  build-zip:
    name: Build ZIP (Win/Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Install Ant
        run: sudo apt-get update && sudo apt-get install -y ant

      - name: Build with Ant
        run: ant clean build

      - name: Ensure executable flags
        run: chmod +x bin/fastqc

      - name: Stage distribution folder
        run: |
          rm -rf FastQC
          mkdir -p FastQC
          cp -a bin/. FastQC/

      - name: Determine version
        id: vars
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ github.event.inputs.tag_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Create ZIP archive
        run: zip -r "fastqc_${{ steps.vars.outputs.version }}.zip" FastQC

      - name: Upload asset to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: fastqc_${{ steps.vars.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact (manual run)
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: fastqc_${{ steps.vars.outputs.version }}.zip
          path: fastqc_${{ steps.vars.outputs.version }}.zip

  build-dmg:
    name: Build DMG (macOS)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Install Ant
        run: brew update && brew install ant

      - name: Build with Ant
        run: ant clean build

      - name: Ensure executable flags
        run: chmod +x bin/fastqc

      - name: Stage distribution folder
        run: |
          rm -rf FastQC
          mkdir -p FastQC
          cp -a bin/. FastQC/

      - name: Determine version
        id: vars
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ github.event.inputs.tag_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Create DMG image
        run: |
          hdiutil create -volname "FastQC" -srcfolder FastQC -ov -format UDZO "fastqc_${{ steps.vars.outputs.version }}.dmg"

      - name: Upload asset to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: fastqc_${{ steps.vars.outputs.version }}.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact (manual run)
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: fastqc_${{ steps.vars.outputs.version }}.dmg
          path: fastqc_${{ steps.vars.outputs.version }}.dmg


